-- init.sql
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS WP_CAMPUS CASCADE;
DROP TABLE IF EXISTS WP_DEPT_GRP CASCADE;
DROP TABLE IF EXISTS WP_DEPT CASCADE;
DROP TABLE IF EXISTS WP_ENTITY CASCADE;
DROP TABLE IF EXISTS WP_ENTRY CASCADE;

SET FOREIGN_KEY_CHECKS = 1;



CREATE TABLE WP_CAMPUS(
   CAMPUS_CODE VARCHAR(8) NOT NULL,
   CAMPUS_NAME VARCHAR(40),
   PRIMARY KEY (CAMPUS_CODE)
);
create table WP_DEPT_GRP(
   DEPT_GRP VARCHAR(6) NOT NULL,
   DEPT_GRP_NAME VARCHAR(60) UNIQUE,
   CAMPUS_CODE VARCHAR(6),
   primary key (DEPT_GRP),
   FOREIGN KEY (CAMPUS_CODE) REFERENCES WP_CAMPUS(CAMPUS_CODE) ON DELETE CASCADE
);
CREATE TABLE WP_DEPT(
   DEPT_ID INT NOT NULL AUTO_INCREMENT,
   DEPT_NAME VARCHAR(60),
   DEPT_GRP VARCHAR(6),
   PRIMARY KEY (DEPT_ID),
   FOREIGN KEY (DEPT_GRP) REFERENCES WP_DEPT_GRP(DEPT_GRP) ON DELETE CASCADE
);
CREATE TABLE WP_ENTITY(
   WP_ID INT NOT NULL AUTO_INCREMENT,
   NAME VARCHAR(90),
   UHUUID VARCHAR(8),
   DELETED VARCHAR(1),
   DELETE_DATE DATE,
   UPDATED VARCHAR(1),
   PRIMARY KEY(WP_ID)
);
create table WP_ENTRY(
   WP_ID INT NOT NULL,
   DEPT_ID INT NOT NULL,
   EMAIL VARCHAR(90),
   TITLE VARCHAR(100),
   PRIMARY KEY (WP_ID,DEPT_ID),
   FOREIGN KEY (WP_ID) REFERENCES WP_ENTITY(WP_ID) ON DELETE CASCADE,
   FOREIGN KEY (DEPT_ID) REFERENCES WP_DEPT(DEPT_ID) ON DELETE CASCADE
);
